### PR TITLE
4.0.8 - Bug Fixes

### PR DESCRIPTION
**Pull request by dostuffthatmatters**
- [x] Freeze the poetry dependencies to the one used in `4.0.7`
- [x] #151
- [x] Remove git commit sha from emails
- [x] #126 
- [x] #125 
- [x] #154
- [x] #157 
- [x] #165
- [x] #156

### CODE REVIEW

**Comment by dostuffthatmatters** [comment]
@patrickjaigner Python needs an exact version (3.10 is not valid, but 3.10.6 is). However, we don't know which Python version existing users have installed (the docs don't specify a minor release: https://pyra.esm.ei.tum.de/docs/user-guide/setup#python-310). Therefore, I added the 3.10.* only for the Python version. But Python itself definitely keeps their semantic versioning straight.

**Review by patrickjaigner — COMMENTED** [review]
Looks good.

**Comment by dostuffthatmatters** [comment]
I rebased this branch to the latest main branch (extended documentation). That is why I force-pushed it.

**Review by patrickjaigner — CHANGES_REQUESTED** [review]
Regarding #155 I'm not too fond of this change. It doesn't address the core issue and force closes all currently running OPUS instances. It also introduces a new method of closing OPUS in addition to the already existing one.
There is an easier solution for it.

**Comment by dostuffthatmatters** [comment]
> Regarding #155 I'm not too fond of this change. It doesn't address the core issue and force closes all currently running OPUS instances. It also introduces a new method of closing OPUS in addition to the already existing one. There is an easier solution for it.

Sure, then I will comment out the changes from #155, and we can do that in a later release, once we know how to fix this elegantly.

**Pull request merged**
